---
site_name: Digital Garden
site_description: My personal digital garden
site_author: Dung Tran
site_url: https://omegakid1902.github.io
nav:
  - Introduction: 🏡 Enter the garden.md
  - Home: 🏡 Enter the garden.md
  - Kinh Thánh: The Bible.md
  - Lịch sử:
      - Lịch sử Việt Nam: 
          - Lịch Sử Việt Nam.md
          - Âu Lạc: Âu Lạc.md
      - Lịch sử Trung Quốc:
          - Lịch Sử Việt Nam.md
          - Nhà Thương: Nhà Thương.md
          - Nhà Chu: Nhà Chu.md
  - Contact: contact.md

plugins:
  - search
      #prebuild_index: true
  - roamlinks
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter 

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
#  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

extra:
  social:
#    - icon: fontawesome/brands/github-alt
#      link: https://github.com/lyz-code
#    - icon: fontawesome/solid/rss
#      link: https://lyz-code.github.io/blue-book/newsletter/0_newsletter_index

repo_name: github.io
repo_url: https://github.com/omegakid1902/omegakid1902.github.io
