---
name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: 11 06 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Number of commits to fetch. 0 indicates all history.
          # Default: 1
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Submodule
        run: |
          git branch
          echo Day la branch nhe!!!!!!!!
          git clone https://github.com/omegakid1902/zettelkasten.git
          cd zettelkasten
          git branch
          echo Day la branch zettelkasten nhe!!!!!!!!
          #git submodule update


        

